First homework done
qeumo/RecoService pull request #3
Opened 2022-11-24 13:56 UTC by qeumo

2022-11-24 14:25 UTC, qeumo commented
@groundmax Please check

2022-11-25 18:29 UTC, groundmax requested changes
Код хороший, но можно сделать лучше

2022-11-25 18:29 UTC, groundmax commented on service/api/exception_handlers.py
> +        return create_response(status_code=401, errors=[error])
Лучше делать отдельный класс для ошибок в exceptions.py, по аналогии как с `ModelNotFoundError`.

2022-11-25 18:29 UTC, groundmax commented on service/api/views.py
> +        404: {
А для 401 ошибки?

2022-11-25 18:29 UTC, groundmax commented on service/auth_bearer.py
> +        self.token_template = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9" \
Токен хранят обычно в переменных окружения

2022-11-25 18:29 UTC, groundmax commented on service/auth_bearer.py
> +                raise HTTPException(status_code=403,
Там тонкая грань, но обычно 401 бросают, если проблема с токеном (просрочился или неправильный), т.е. доступ можно получить, если исправить токен. 403 бросают, если даже с нормальным токеном не будет доступа к странице.

2022-11-27 09:28 UTC, qeumo commented on service/api/views.py
> +        404: {
Добавил 401

2022-11-27 09:28 UTC, qeumo commented on service/auth_bearer.py
> +        self.token_template = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9" \
Переместил в JWT_TOKEN

2022-11-27 09:29 UTC, qeumo commented on service/auth_bearer.py
> +                raise HTTPException(status_code=403,
Поменял на 401

2022-11-28 14:27 UTC, groundmax requested changes
Ребят, пожалуйста, не отправляйте на ПР, если CI/CD не прошел (должно гореть зеленым цветом)
<img width="918" alt="image" src="https://user-images.githubusercontent.com/36198818/204302287-68f4e600-470d-4f73-94fe-d62edd240316.png">

2022-11-28 14:27 UTC, groundmax commented on Makefile
> +lint: isort flake pylint
Почему mypy убрали?

2022-11-28 14:27 UTC, groundmax commented on service/gdown_utils.py
> +def download_file_from_google_drive(file_id, destination):
аннотации для параметров и возвращаемых функций? Аналогично для всех функций, теперь я понял почему вы убрали mypy))

2022-11-28 14:27 UTC, groundmax commented on service/auth_bearer.py
> +        self.token_template = os.environ.get("JWT_TOKEN", None)
Лучше использовать os.environ["JWT_TOKEN"], он упадет в случае, если переменная окружения не задана.
Плюс, по умолчанию get() и так возвращает None

2022-11-28 14:27 UTC, groundmax commented on tests/api/test_views.py
> +TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9" \
А этот токен почему вы здесь оставили? Его же тогда нужно брать из переменных окружения)

2022-11-28 14:27 UTC, groundmax commented on service/auth_bearer.py
> +                raise HTTPException(status_code=403,
А здесь почему не заменили статус? Плюс, если уж совсем-совсем по-хорошему (не обязательно, но приветствуется) использовать: https://docs.python.org/3/library/http.html

то есть `status_code=HTTPStatus.UNAUTHORIZED`

2022-11-28 14:27 UTC, groundmax commented on tests/api/test_views.py
> +def test_get_reco_for_unknown_model(
Пишу здесь, просто, чтобы было именно комментарий в коде. Давайте возьмем за правило, что проверяющему можно максимум два раза отправлять на ревью. То есть это последняя попытка, больше отправлять на корректировку не буду.

2022-11-29 06:37 UTC, merged