Hw2
qeumo/RecoService pull request #4
Opened 2022-11-28 16:31 UTC by qeumo

Check nic's version please

2022-11-29 23:04 UTC, groundmax requested changes
Ребят, в целом все хорошо, есть небольших замечания. Пожалуйста, отправляйте только одно решение дз, плюс не нужно включать информацию с семинара. Нужны только описание задачи с семинара и ваши решения с пояснениями, где это необходимо. В папке `nic's version` все как и должно быть, но в папке `hw2` очень много лишнего (его я и не смотрел)

2022-11-29 23:04 UTC, groundmax commented on notebooks/hw2/nic`s version/MRR.ipynb
> +    "    return sum(mrr) / len(users)"
Зачем хранить массив, если можно на ходу считать кумулятивную сумму?

2022-11-29 23:04 UTC, groundmax commented on notebooks/hw2/nic`s version/MRR.ipynb
> +    "                user_mrr = 1 / (j + 1)\n",
В enumerate можно сделать так, чтобы начинался счет с 1, тогда не нужно самому писать + 1

2022-11-29 23:04 UTC, groundmax commented on notebooks/hw2/nic`s version/MRR.ipynb
> +    "    mrr = df_recs.groupby('user_id')['reciprocal_rank'].max().sum() / len(users)\n",
Можно воспользоваться `.mean()` вместо .`.sum() / len(users)`

P.S. FYI, по умолчанию groupby всегда сортирует группы, можете поиграться, посмотреть как скорость изменится (к домашке напрямую не относится). Если не хотите - можете не делать.

2022-11-29 23:04 UTC, groundmax commented on notebooks/hw2/nic`s version/PFound.ipynb
> +    "    qid_top_k_hostid['one_minus_rating'] = (1 - qid_top_k_hostid['rating']).shift(1)\n",
А что будет если в параметрах `shift` поставить fill_value=0? Как это повлияет на результаты?

2022-12-02 06:50 UTC, Altair7610 commented on notebooks/hw2/nic`s version/PFound.ipynb
> +    "    qid_top_k_hostid['one_minus_rating'] = (1 - qid_top_k_hostid['rating']).shift(1)\n",
Если установить fill_value в 0, значения для новых неустановленных позиций будет ставиться в 0, а не в NaN. Результат не изменится, т.к. значение NaN выпадает только в первой строке фрейма и далее по коду это обрабатывается, колонки one_minus_p_break и one_minus_rating выставляются в единицу

2022-12-02 07:12 UTC, Altair7610 commented on notebooks/hw2/nic`s version/MRR.ipynb
> +    "    return sum(mrr) / len(users)"
Done

2022-12-02 07:12 UTC, Altair7610 commented on notebooks/hw2/nic`s version/MRR.ipynb
> +    "                user_mrr = 1 / (j + 1)\n",
Done

2022-12-02 07:12 UTC, Altair7610 commented on notebooks/hw2/nic`s version/MRR.ipynb
> +    "    mrr = df_recs.groupby('user_id')['reciprocal_rank'].max().sum() / len(users)\n",
Done

2022-12-02 16:33 UTC, groundmax approved these changes
Все хорошо, молодцы!

2022-12-09 14:32 UTC, merged