hw4
qeumo/RecoService pull request #7
Opened 2022-12-12 16:12 UTC by qeumo

Вся работа в Homework_4.ipynb

Сервис отдает рекомендации в режиме online через ANN индекс в Qdrant

MAP@10 = 0.88

2022-12-12 19:54 UTC, groundmax requested changes
Лишний раз напомню, не оставляйте, пожалуйста, мои комментарии пустыми. Если попроваили - отпишитесь Done/Fixed, не поправили - тоже что-нибудь отпишите, например, почему итп

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "### 1st user: Horror Person"
Касательно аватаров, почему решили добавить именно таких пользователей?

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "horror_person_intercations = horror_interactions.item_id.unique()[:5]"
А какие в итоге фильмы он посмотрел? У вас просто выведены айдишники, но, хотелось бы полную инфу: название, год выпуска, режиссер итд. Насколько популярные это фильмы? Аналогично для других аватаров.
На самом деле это лучше выводить при просмотре итоговых рекомендаций, так как это удобнее: рядом история просмотров и текущие рекомендации.

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "def objective(trial: optuna.Trial, reco_algorithm):\n",
В целом, если бы вы работали над каким-то реальный продуктом, то считать на одном сплите - не очень хорошо, перебирать гиперпараметры лучше по кросс валидации. Плюс, вы просто убрали холодных пользователей из теста - тоже не очень хорошо. Но так как это учебное задание, пока прощаем)

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "    'USER_ALPHA': {'values': (0, 0), 'dtype': 'int'}, # Lightfm\n",
Почему от 0 до 0?

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "    time.sleep(1)\n",
Зачем sleep?

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "model.fit(dataset)"
Почему не обучились на всем датасете (train+test)?

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "#### Рекомендации для 1 аватара - Horror Person"
Можно, пожалуйста, прокомментировать получившиеся результаты?

2022-12-12 19:54 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "items[items.item_id.isin(avatars_reco_item_ids[1097558])]"
isin выводит не в порядке, который указан у вас, а в том, порядке в каком лежали в датасете. Сравните порядок айдишников в реко от Qdrant и то, что выведено у вас. Нужно вывести именно в том порядке, в котором отдал Qdrant. Плюс, пожалуйста, добавьте колонку, которая характеризует популярность фильма.

2022-12-12 19:54 UTC, groundmax commented on service/api/app.py
> +user_dataset_filename = 'user_dataset.pkl'
лучше такие штуки выносить куда-нибудь в конфиг

2022-12-12 19:54 UTC, groundmax commented on service/api/app.py
> +cold_reco = pickle.load(open(cold_reco_filename, 'rb'))
Лучше использовать контекстный менеджер для работы с файлами, плюс лучше написать функу для загрузки из пикла

2022-12-12 19:54 UTC, groundmax commented on service/api/views.py
> +    except Exception:
qdrant же наверняка выдает какую-то конкретную ошибку, если idшник не найден в коллекции. Лучше обрабатывать конкретно ее. В общем, использование Exception, конечно, допускается, но его лучше избегать, поэтому линтеры были правы, когда ругались на это. В вашем случае точно Exception не нужен. Так что расскоментируйте игнор линтеров "broad-except" и замените здесь тип ошибки. Just FYI, для pylint можно игнорировать конкретную строчку, а не игнорировать ошибку вовсе.

2022-12-12 19:54 UTC, groundmax commented on service/db/ann_index.py
> +                          payload: list = None,
typing.List?

2022-12-12 19:54 UTC, groundmax commented on Dockerfile
> +ENV JWT_TOKEN eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2Njg4NjExNTQsImV4cCI6MTcwMDM5NzE1NCwiYXVkIjo
Токены так не хранят, если нужно прокинуть чувствительную информацию то, можно, например, сделать [так](https://stackoverflow.com/a/31756244)

2022-12-13 09:36 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "### 1st user: Horror Person"
Когда добавляли пользователей руководствовались делением предпочтений по категориям фильмов, поэтому у нас любитель ужастиков 18+, любитель комедий 16+ и для разнообразия мать с ребенком, который любит мультфильмы 0+.
Для всех категорий использовали фильтр watched_pct > 80 - пользователь посмотер значительную часть фильма, следовательно можем предположить, что у него есть интерес к таким фильмам.

2022-12-13 09:40 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "horror_person_intercations = horror_interactions.item_id.unique()[:5]"
В данном ноутбуке секция с выводом рекомендаций по аватарам находится ближе к концу, так как для выдачи рекомендаций необходимо обучить модель и построить ANN индекс. 
Добавил в секцию аватаров более детальную информацию по истории просмотров.

2022-12-13 09:41 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "def objective(trial: optuna.Trial, reco_algorithm):\n",
Согласен с вами

2022-12-13 09:43 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "    'USER_ALPHA': {'values': (0, 0), 'dtype': 'int'}, # Lightfm\n",
Сначала запускал поиск от 0 до 10, но он очень долго учился и в итоге обнулил перебор этого параметра. Оставил в коде, чтобы показать возможность перебора и этого параметра.

2022-12-13 09:45 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "    time.sleep(1)\n",
Были проблемы с оптимайзом study, нашел данное решение и попробовал - получилось решить. Может быть проблемы были в другом, но в любом случае решил их, а sleep оставил на всякий.

2022-12-13 09:49 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "model.fit(dataset)"
Обучение везде проводили на train данных, а на test оценивали метрики.

2022-12-13 11:41 UTC, qeumo commented on Dockerfile
> +ENV JWT_TOKEN eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2Njg4NjExNTQsImV4cCI6MTcwMDM5NzE1NCwiYXVkIjo
Исправил

2022-12-13 11:41 UTC, qeumo commented on service/db/ann_index.py
> +                          payload: list = None,
Исправил

2022-12-13 11:41 UTC, qeumo commented on service/api/views.py
> +    except Exception:
Исправил

2022-12-13 11:41 UTC, qeumo commented on service/api/app.py
> +cold_reco = pickle.load(open(cold_reco_filename, 'rb'))
Исправил

2022-12-13 11:42 UTC, qeumo commented on service/api/app.py
> +user_dataset_filename = 'user_dataset.pkl'
Ок, вынес

2022-12-13 11:42 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "items[items.item_id.isin(avatars_reco_item_ids[1097558])]"
Спасибо, не заметил этого изначально. Исправил.

2022-12-13 12:16 UTC, qeumo commented on notebooks/hw4/Homework_4.ipynb
> +    "#### Рекомендации для 1 аватара - Horror Person"
Добавил комментарии в ноутбук

2022-12-13 13:01 UTC, qeumo commented
По всем пунктам дал ответ и исправил код.
Ответы для пользователей 425823, 964868, 327683, 524297 прикрепляю:
![image](https://user-images.githubusercontent.com/25222172/207287976-653f8871-f894-43a0-9432-ee6095d40071.png)

2022-12-13 15:43 UTC, groundmax commented on notebooks/hw4/Homework_4.ipynb
> +    "model.fit(dataset)"
Итоговую модель можно было обучить на всех данных, сейчас у вас в проде модель, у которой просто выкинута часть данных без особой причины)

2022-12-13 15:47 UTC, groundmax commented on service/db/ann_index.py
> +                          payload: list = None,
Обычно принято писать что хранит в себе список: str, int, float. Так легче понять как работает код, особенно когда его много

2022-12-13 15:57 UTC, groundmax approved these changes
Не очень хорошо, что вы обучились не на всем датасете по итогу, но то, что сделали рекомендации через ANN - очень хорошо, даже не смотря на то, что выдается простое популярное. Баллы смотрите в таблице

2022-12-13 16:53 UTC, merged